config/routes.rb
LiveclippingsFront::Application.routes.draw do

  root :to => 'pages#home'

  match '/about', :to => 'pages#about'
  match '/clipping/copy/:id',    :to => 'clippings#copy'
  match '/clipping/create',      :to => 'clippings#create'
  match '/clipping/delete/:id',  :to => 'clippings#delete'
  match '/clipping/destroy/:id', :to => 'clippings#destroy'
  match '/clipping/edit/:id',    :to => 'clippings#edit'
  match '/clipping/new',         :to => 'clippings#new'
  match '/clipping/show/:id',    :to => 'clippings#show'
  match '/clipping/update/:id',  :to => 'clippings#update'
  match '/clippings',            :to => 'clippings#list'
  match '/clippings/page/:page', :to => 'clippings#list'
  match '/clippings/search/:search',            :to => 'clippings#list'
  match '/clippings/search/:search/page/:page', :to => 'clippings#list'
  match '/contact',         :to => 'pages#contact'
  match '/feedback',        :to => 'pages#feedback'
  match '/follow/:id',      :to => 'followings#follow'
  match '/followings',      :to => 'followings#followings'
  match '/forgot_password', :to => 'pages#forgot_password'
  match '/help',            :to => 'pages#help'
  match '/login',           :to => 'access#attempt_login'
  match '/password_reset/:id',  :to => 'pages#password_reset'
  match '/profile',             :to => 'users#show'
  match '/profile/edit/:id',    :to => 'users#edit'
  match '/profile/delete/:id',  :to => 'users#delete'
  match '/profile/destroy/:id', :to => 'users#destroy'
  match '/profile/update/:id',  :to => 'users#update'
  match '/search',            :to => 'followings#search'
  match '/signin',            :to => 'access#login'
  match '/signout',           :to => 'access#logout'  
  match '/signup',            :to => 'users#new'
  match '/signup/create',     :to => 'users#create'
  match '/stream',            :to => 'clippings#stream'
  match '/stream/page/:page', :to => 'clippings#stream'
  match '/unfollow/:id',      :to => 'followings#delete'

end

app/views/layouts/public.html.erb
<!doctype html>
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
  <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
  <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
  <!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Live Clippings<%= " | #{@page_title}" if @page_title %></title>
    <link href='http://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag('smoothness/jquery-ui-1.8.16.custom', 'bootstrap.min', 'style', 'bootstrap-responsive.min', :media => 'all') %>
    <%= javascript_include_tag('libs/modernizr-2.0.6.min') %>
    <%= csrf_meta_tag %>
  </head>
  <body>
      <!--[if lt IE 9]>
        <div id="iewarningbox">
          Please consider upgrading your browser. I hear <a href="https://www.google.com/chrome/eula.html?&brand=CHMA&utm_campaign=en&utm_source=en-ha-na-us-bk&utm_medium=ha&installdataindex=homepagepromo">Google Chrome</a> is really cool!
        </div>
      <![endif]-->
    <div class="container">
      <header>
        <div class="left beta-ribbon-holder">
          <%= link_to feedback_path, :class => "blue beta-ribbon" do %>
            <%= content_tag(:span, "In Beta! Feedback is appreciated.", :class => "text") %>
          <% end %>
        </div>
        <%= link_to image_tag('logo.png', :alt => 'LiveClippings', :class => 'logo round'), root_path %>
        <nav class="top round box">
          <ul>
            <% if current_user %>
              <li><%= link_to("Stream", stream_path) %></li>
              <li><%= link_to("Clippings", clippings_path) %></li>
              <li><%= link_to("Followings", followings_path) %></li>
              <li><%= link_to("Profile", profile_path) %></li>
              <li><%= link_to("Sign out", signout_path) %></li>
            <% else %>
              <li><%= link_to 'Sign up', signup_path %></li>
              <li><%= link_to 'Sign in', signin_path %></li>
              <li><%= link_to 'Forgot Password', forgot_password_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <section id="main" role="main" class="clearfix round box">
        <% if !flash[:notice].blank? %>
          <div class="notice">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= yield %>
      </section>  
      <div class="clearfix"></div>
      <footer class="right-align round box">
        <span id="copyright">&copy; 2011 / 
          <%= link_to '@mattweppler', 'http://twitter.com/#!/mattweppler' %> / 
        </span>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Feedback", feedback_path %></li>
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </nav>
      </footer>
    <%= content_tag("div", debug(params), :id => "rails-debug") if Rails.env.development? %>
  </div> <!--! end of #container -->

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="javascript/libs/jquery-1.7.1.min.js"><\/script>')</script>

  <!-- scripts concatenated and minified via ant build script-->
  <%= javascript_include_tag('plugins', 'libs/jquery-ui-1.8.16.custom.min', 'script', 'libs/application', 'libs/bootstrap.min', 'libs/rails') %>
  <!-- end scripts-->

  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
    <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
  <![endif]-->

  </body>
</html>